build:
  image: python:3
  commands:
    - echo "Building data service."
  run_tests:
        image: python:3-alpine
        commands:
            - pip install -r requirements.txt


publish:
  docker:
    repo: $$DOCKER_USERNAME/qosmanagerbot
    tag: latest
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL


deploy:
  webhook:
    image: plugins/drone-webhook
    skip_verify: true
    method: POST
    auth:
      username: $$MANTL_USERNAME
      password: $$MANTL_PASSWORD
    urls:
      - https://$$MANTL_CONTROL/marathon/v2/apps/$$DEPLOYMENT_DIR/$$DOCKER_USERNAME/$$BOT_NAME/restart?force=true
    when:
      branch: "master"


notify:
  spark:
    image: hpreston/drone-spark
    auth_token: $$SPARK_TOKEN
    roomId: $$SPARK_ROOM
